{{- if and .Values.elastic.enabled .Values.solr.enabled }}
  {{ fail "Both SOLR and elastic search systems are enabled, you can only have 1 (or none) enabled." }}
{{- end }}
# Defines the properties required by the content repository
apiVersion: v1
kind: ConfigMap
metadata:
  name: acs-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: acs
data:
  DB_URL: {{ quote .Values.acs.dbUrl }}
  DB_DRIVER: {{ quote .Values.acs.dbDriver }}
  {{- if .Values.share.enabled }}
  SHARE_HOST: {{ quote .Values.ingress.host }}
  SHARE_PORT: {{ quote .Values.acs.sharePort }}
  SHARE_PROTOCOL: {{ quote .Values.acs.shareProtocol }}
  {{- end }}
  {{- if .Values.solr.enabled }}
  SOLR_HOST: 'solr-service'
  {{- end }}
  {{- if .Values.syncService.enabled }}
  GLOBAL_dsync.service.uris: '{{ .Values.ingress.protocol }}://{{ .Values.ingress.syncServiceHost }}/alfresco'
  {{- end }}
  {{- if .Values.mq.enabled }}
  GLOBAL_messaging.broker.url: 'failover:(nio://mq-service:61616)?timeout=3000&jms.useCompression=true'
  {{- end }}
  {{- if and (gt .Values.acs.replicas 1.0)  (.Values.general.enterprise) }}
  GLOBAL_alfresco.cluster.enabled: 'true'
  #turn off hazelcast phone home
  HZ_PHONE_HOME_ENABLED: 'false'
  {{- end }}
  {{- if not (.Values.general.enterprise) }}
  GLOBAL_local.transform.service.enabled: 'true'
  {{- end}}
  {{- if .Values.transformServices.enabled }}
  GLOBAL_transform.service.enabled: 'true'
  {{- if .Values.transformServices.transformRouter.enabled }}
  GLOBAL_transform.service.url: 'http://transform-router-service:30500'
  {{- end }}
  {{- if .Values.transformServices.sharedFileStore.enabled }}
  GLOBAL_sfs.url: 'http://shared-file-store-service:80/'
  {{- end }}
  {{- if .Values.transformServices.transformCoreAio.enabled }}
  GLOBAL_localTransform.core-aio.url: 'http://transform-core-aio-service:80/'
  {{- end }}
  {{- else }}
  GLOBAL_transform.service.enabled: 'false'
  {{- end }}
  GLOBAL_aos.baseUrlOverwrite: '{{ .Values.ingress.syncServiceHost }}://{{ .Values.ingress.host }}/alfresco/aos'
  {{- if .Values.solr.enabled }}
  GLOBAL_index.subsystem.name: "solr6"
  GLOBAL_solr.port: '30300'
  {{- else if .Values.elastic.enabled }}
  GLOBAL_index.subsystem.name: "elasticsearch"
  GLOBAL_elasticsearch.host: {{ .Values.elastic.host | quote }}
  GLOBAL_elasticsearch.port: {{ .Values.elastic.port | quote }}
  GLOBAL_elasticsearch.indexName: {{ coalesce (((.Values.global).elasticsearch).indexName)  (((.Values.elastic).elasticsearch).indexName) (printf "alfresco-%s" .Release.Namespace ) | quote }}
  GLOBAL_elasticsearch.createIndexIfNotExists: {{ .Values.elastic.createIndexIfNotExists | quote }}
  {{- else }}
  GLOBAL_index.subsystem.name: "noindex"
  {{- end }}
  {{- if ((((.Values.acs).email).inbound).port) }}
  GLOBAL_email.server.port: {{ .Values.acs.email.inbound.port }}
  {{- end }}
  {{- if .Values.acs.additionalEnvironmentVariables }}
  {{ toYaml .Values.acs.additionalEnvironmentVariables | nindent 2 }}
  {{- end }}