{{- if .Values.acs.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: acs-hpa
  namespace: {{ .Release.Namespace | quote }}
{{- with .Values.acs.hpa }}
spec:
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- if .cpu.enabled }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .cpu.utilization }}
    {{- end }}
    {{- if .memory.enabled }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .memory.utilization }}
    {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acs
{{- end }}
{{- end }}