apiVersion: v1
kind: Secret
metadata:
  name: acs-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if .Values.mq.enabled }}
  GLOBAL_messaging.broker.username: {{ required "if mq is enabled you need to provide a username for the mq in values.mq.adminLogin" .Values.mq.adminLogin | b64enc }}
  GLOBAL_messaging.broker.password: {{ required "if mq is enabled you need to provide a password for the mq in values.mq.adminPassword" .Values.mq.adminPassword | b64enc }}
  {{- end }}