# Defines the deployment for the alfresco content repository app
apiVersion: v1
kind: Service
metadata:
  name: acs-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.acs.serviceAnnotations }}
    {{ toYaml .Values.acs.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: acs
  ports:
      - name: 'acs'
        protocol: TCP
        port: 30000
        targetPort: 8080
      - name: 'acs-ssl'
        protocol: TCP
        port: 8443
        targetPort: 8443
  {{- if .Values.general.serviceType }}
  type: {{ .Values.general.serviceType }}
  {{- end }}