apiVersion: v1
kind: Secret
metadata:
  name: acs-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if .Values.acs.s3Datastore.enabled }}
  GLOBAL_objectstorage.store.myS3ContentStore.value.accessKey: {{ required "Since you enabled S3 ContentStore you need to pass an accessKey and secretKey in acs.s3Datastore.accessKey/acs.s3Datastore.secretKey" .Values.acs.s3Datastore.accessKey }}
  GLOBAL_objectstorage.store.myS3ContentStore.value.secretKey: {{ required "Since you enabled S3 ContentStore you need to pass an accessKey and secretKey in acs.s3Datastore.accessKey/acs.s3Datastore.secretKey" .Values.acs.s3Datastore.secretKey }}
  {{- end }}