# Defines the deployment for the alfresco content repository app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: acs
spec:
  {{- if .Values.general.hibernate }}
  replicas: 0
  {{- else if  .Values.general.enterprise }}
  replicas: {{ .Values.acs.replicas }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: acs
  strategy:
    {{- if eq .Values.acs.strategy.type "Recreate" }}
    type: {{ .Values.acs.strategy.type }}
    {{- else }}
    {{ toYaml .Values.general.strategy | nindent 4 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: acs
      annotations:
        checksum/acs-config: {{ include (print $.Template.BasePath "/acs/acs-config.yaml") . | sha256sum }}
        checksum/db-secret: {{ include (print $.Template.BasePath "/db-secret.yaml") . | sha256sum }}
        {{- if .Values.mq.enabled }}
        checksum/mq-secret: {{ include (print $.Template.BasePath "/active-mq/mq-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.share.mergeAcsShare }}
        checksum/share-config: {{ include (print $.Template.BasePath "/share/share-config.yaml") . | sha256sum }}
        {{- if .Values.share.podAnnotations }}
        {{ toYaml .Values.share.podAnnotations | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- include "globalPodAnnotations" . | indent 8 }}
        {{- if .Values.acs.podAnnotations }}
        {{ toYaml .Values.acs.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.acs.serviceAccount }}
      serviceAccountName: {{ .Values.acs.serviceAccount }}
      {{- end }}
      containers:
      - name: acs-container
        image: {{ .Values.acs.image.registry }}/{{ .Values.acs.image.repository }}:{{ .Values.acs.image.tag }}
        imagePullPolicy: {{ .Values.acs.imagePullPolicy | default "IfNotPresent" }}
        {{- if .Values.acs.customReadinessProbe }}
        readinessProbe:
          {{ toYaml .Values.acs.customReadinessProbe | nindent 10 }}
        {{- else if .Values.acs.readinessProbe }}
        readinessProbe:
          {{ toYaml .Values.acs.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.acs.customLivenessProbe }}
        livenessProbe:
          {{ toYaml .Values.acs.customLivenessProbe | nindent 10 }}
        {{- else if .Values.acs.livenessProbe }}
        livenessProbe:
          {{ toYaml .Values.acs.livenessProbe | nindent 10 }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 20
        envFrom:
          - configMapRef:
              name: acs-configmap
          - secretRef:
              name: db-secret
          {{- if .Values.mq.enabled }}
          - secretRef:
              name: mq-secret
          {{- end }}
          {{- if .Values.acs.envFrom }}
          {{ toYaml .Values.acs.envFrom | nindent 10 }}
          {{- end }}
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 5701
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
        {{- if or (.Values.acs.resources.requests) ((.Values.acs.resources.limits)) }}
        resources:
          {{- if .Values.acs.resources.requests }}
            requests:
            {{ toYaml .Values.acs.resources.requests | nindent 14 }}
          {{- end }}
          {{- if .Values.acs.resources.limits }}
            limits:
            {{ toYaml .Values.acs.resources.limits | nindent 14 }}
          {{- end }}
        {{- end }}
        volumeMounts:
        {{- if .Values.persistentStorage.alfresco.enabled }}
          - name: data
            mountPath: /opt/alfresco/alf_data
            subPath: alfresco/data
        {{- end }}
        {{- if .Values.persistentStorage.alfresco.additionalClaims }}
        {{- range .Values.persistentStorage.alfresco.additionalClaims }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            subPath: {{ .subPath }}
        {{- end }}
        {{- end }}
        {{- if .Values.acs.additionalVolumeMounts }}
        {{- toYaml .Values.acs.additionalVolumeMounts | nindent 10 }}
        {{- end }}
      {{- if .Values.share.mergeAcsShare}}
      - name: share-container
        image: {{ .Values.share.image.registry }}/{{ .Values.share.image.repository }}:{{ .Values.share.image.tag }}
        imagePullPolicy: {{ .Values.share.imagePullPolicy | default "IfNotPresent" }}
        readinessProbe:
          failureThreshold: {{ .Values.share.readinessProbe.failureThreshold }}
          httpGet:
            path: /share
            port: 8082
            scheme: HTTP
          initialDelaySeconds: {{ .Values.share.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.share.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.share.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.share.readinessProbe.timeoutSeconds }}
        livenessProbe:
          failureThreshold: {{ .Values.share.livenessProbe.failureThreshold }}
          httpGet:
            path: /share
            port: 8082
            scheme: HTTP
          initialDelaySeconds: {{ .Values.share.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.share.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.share.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.share.livenessProbe.timeoutSeconds }}
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 20
        envFrom:
          - configMapRef:
              name: share-configmap
          {{- if .Values.share.envFrom }}
          {{ toYaml .Values.share.envFrom | nindent 10 }}
          {{- end }}
        ports:
          - containerPort: 8082
            # when running together with acs we fix containerport for share to 8082, see also TOMCAT-PORT
            protocol: TCP
        {{- if or (.Values.share.resources.requests) ((.Values.share.resources.limits)) }}
        resources:
          {{- if .Values.share.resources.requests }}
          requests:
          {{ toYaml .Values.share.resources.requests | nindent 12 }}
          {{- end }}
          {{- if .Values.share.resources.limits }}
          limits:
          {{ toYaml .Values.share.resources.limits | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      {{- if .Values.persistentStorage.alfresco.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ default "alfresco" .Values.persistentStorage.alfresco.name }}-pvc
      {{- end }}
      {{- if .Values.persistentStorage.alfresco.additionalClaims }}
      {{- range .Values.persistentStorage.alfresco.additionalClaims }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
      {{- end }}
      {{- end }}
      {{- if .Values.acs.additionalVolumes }}
        {{ toYaml .Values.acs.additionalVolumes | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        {{- if .Values.general.imagePullSecrets}}
        {{ toYaml .Values.general.imagePullSecrets | nindent 8 }}
        {{- end }}
        {{- if .Values.acs.imagePullSecrets}}
        {{ toYaml .Values.acs.imagePullSecrets | nindent 8 }}
        {{- end }}
        {{- if .Values.share.mergeAcsShare}}
        {{- if .Values.share.imagePullSecrets }}
        {{ toYaml .Values.share.imagePullSecrets | nindent 8 }}
        {{- end }}
        {{- end }}
      {{- if .Values.acs.initContainers }}
      initContainers:
        {{ toYaml .Values.acs.initContainers | nindent 8 }}
      {{- end }}