---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-postgresql
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgresql
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-mq
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mq
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-transform-core-aio
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: transform-core-aio
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-solr
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: solr
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-sync-service
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: sync-service
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-solr
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: solr
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-share
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: share
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-sync-service
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: sync-service