{{- if .Values.general.networkPolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-postgresql
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgresql
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-mq
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mq
      ports:
        - protocol: TCP
          port: 61616
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-transform-core-aio
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: transform-core-aio
      ports:
        - protocol: TCP
          port: 8090
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-solr
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: solr
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-sync-service
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: sync-service
      ports:
        - protocol: TCP
          port: 9090
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-transform-router
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: transform-router
      ports:
        - protocol: TCP
          port: 8095
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-shared-file-store
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: shared-file-store
      ports:
        - protocol: TCP
          port: 8099
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-solr
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: solr
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-share
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: share
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-sync-service
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: sync-service
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-ooi
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ooi
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-to-acs
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 5701
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: acs-from-acs
spec:
  podSelector:
    matchLabels:
      app: acs
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 5701

---
{{- end }}