{{- if .Values.general.networkPolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: solr-to-acs
spec:
  podSelector:
    matchLabels:
      app: solr
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 30000
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: solr-from-acs
spec:
  podSelector:
    matchLabels:
      app: solr
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 30300
        - protocol: TCP
          port: 8443
{{- end }}