{{- if .Values.solr.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: solr
data:
  SOLR_BACKUP_DIR: '/opt/alfresco-search-services/backup'
  ALFRESCO_HOST: 'acs-service'
  ALFRESCO_PORT: '30000'
  {{- if gt .Values.solr.replicas 1.0 }}
  SHARDING.cluster.enabled: 'true'
  {{- end }}
  {{- if .Values.solr.additionalEnvironmentVariables }}
  {{ toYaml .Values.solr.additionalEnvironmentVariables | nindent 2 }}
  {{- end }}
{{- end }}