{{- if and (.Values.solr.enabled) (gt .Values.solr.replicas 1.0) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: solr-pdb
  namespace: {{ .Release.Namespace | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: solr
{{- end }}