ingress:
  host: test
  protocol: http
  kubernetes.io/ingress.class: {}
acs:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
mq:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
solr:
  enabled: false
transformServices:
  enabled: false
digitalWorkspace:
  enabled: false