ingress:
  host: test
  protocol: http
  kubernetes.io/ingress.class: {}
#  enabling the line below will cause the ingress.class annotation to be rendered instead of the ingressClass property
#  ingressClass: null
acs:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
share:
  mergeAcsShare: true"
mq:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
solr:
  enabled: false
transformServices:
  enabled: false
digitalWorkspace:
  enabled: false

general:
  networkPolicies:
    enabled: false