{{- if and (.Values.general.networkPolicies.enabled) (.Values.ooi.enabled) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: ooi-to-acs
spec:
  podSelector:
    matchLabels:
      app: ooi
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
---
{{- end }}