{{- if .Values.ooi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: ooi-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.ooi.serviceAnnotations }}
    {{ toYaml .Values.ooi.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: ooi
  ports:
    - protocol: TCP
      port: 30500
      targetPort: 9095
  {{- if .Values.general.serviceType }}
  type: {{ .Values.general.serviceType }}
  {{- end }}
{{- end }}