apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  DB_USERNAME: {{ required "You must provide the username of the DB used in values.global.dbUser" .Values.global.dbUser | b64enc }}
  DB_PASSWORD: {{ required "You must provide the password for the DB user in values.global.dbUser" .Values.global.dbPassword | b64enc }}
  POSTGRES_USER: {{ required "You must provide the username of the DB used in values.global.dbUser" .Values.global.dbUser | b64enc }}
  POSTGRES_PASSWORD: {{ required "You must provide the password for the DB user in values.global.dbUser" .Values.global.dbPassword | b64enc }}