apiVersion: v1
kind: Secret
metadata:
  name: privatecred
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "privateImagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: alfrescocred
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "alfrescoImagePullSecret" . }}