apiVersion: v1
kind: Secret
metadata:
  name: privatecred
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  # try to get the old secret and sync-service-configmap
  # keep in mind, that a dry-run only returns an empty map
  {{- $old_private_sec := lookup "v1" "Secret" .Release.Namespace "privatecred" }}

  # check, if a private repo secret isn't already set and no private repo credentials are passed
  {{- if and ($old_private_sec) ($old_private_sec.data) (not .Values.imageCredentials.private.username) (not .Values.imageCredentials.private.password) }}
  .dockerconfigjson: {{ index $old_private_sec.data ".dockerconfigjson" }}
  {{- else }}
  .dockerconfigjson: {{ template "privateImagePullSecret" . }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: alfrescocred
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  # try to get the old secret and sync-service-configmap
  # keep in mind, that a dry-run only returns an empty map
  {{- $old_alfresco_sec := lookup "v1" "Secret" .Release.Namespace "alfrescocred" }}

  # check, if an alfresco repo secret isn't already set and no alfresco repo credentials are passed
  {{- if and ($old_alfresco_sec) ($old_alfresco_sec.data) (not .Values.imageCredentials.alfresco.username) (not .Values.imageCredentials.alfresco.password) }}
  .dockerconfigjson: {{ index $old_alfresco_sec.data ".dockerconfigjson" }}
  {{- else }}
  .dockerconfigjson: {{ template "alfrescoImagePullSecret" . }}
  {{- end }}