# Defines the deployment for the alfresco content repository app

# Collect all host names.
{{- $allAlfrescoHostNames := .Values.ingress.hosts }}
## Add support for the legacy ingress.host property.
{{- if .Values.ingress.host }}
  {{- $allAlfrescoHostNames = append $allAlfrescoHostNames .Values.ingress.host }}
{{- end }}
## At least one Alfresco hostname should be specified.
{{- if eq (len $allAlfrescoHostNames) 0}}
  {{- fail "No host specified for the Alfresco Ingress controller. Please specify the 'values.ingress.hosts' property (list of hostnames)." }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alfresco-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if and (.Values.ingress.clusterIssuer) (not (eq .Values.ingress.clusterIssuer "")) }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    {{- end }}
    {{- if .Values.ingress.ingressAnnotations }}
    {{- /*
      See https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
      Remove kubernetes.io/ingress.class annotation if ingressClass is set
      ingressClass can be removed from defaults by setting ingressClass: null in values override
      Tied to spec.ingressClassName
    */ -}}
    {{- range $key, $value := .Values.ingress.ingressAnnotations }}
    {{- if not ( and ($.Values.ingress.ingressClass) (eq $key "kubernetes.io/ingress.class")) }}
    {{ $key  }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClass }}
  ingressClassName: {{ .Values.ingress.ingressClass }}
  {{- end }}
  {{- if eq .Values.ingress.protocol "https" }}
  tls:
    - hosts:
        # Provide the desired host
        {{- range $allAlfrescoHostNames}}
        - {{ . | quote }}
        {{- end }}
        {{- if .Values.syncService.enabled }}
        - {{ required "If sync Services are enabled a specific host for sync services must be specified in values.ingress.syncServiceHost" .Values.ingress.syncServiceHost }}
        {{- end }}
      # Provide a unique secret to store the SSL credentials
      secretName: tls-alfresco-{{ .Release.Name }}-secret
  {{- end }}
  {{- if  .Values.ingress.defaultBackend }}
  defaultBackend:
    service:
      name: {{ .Values.ingress.defaultBackend.service }}
      port:
        number: {{ .Values.ingress.defaultBackend.port }}
  {{- end }}
  rules:
  {{- range $allAlfrescoHostNames }}
  - host: {{ . | quote }}
    http:
      paths:
      {{- if $.Values.general.hibernate }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-default-service
            port:
              number: 30403
      {{- else if $.Values.ingress.defaultPath }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.ingress.defaultPath.service }}
            port:
              number: {{ $.Values.ingress.defaultPath.port }}
      {{- end }}
      {{- if and $.Values.acs.ingress.enabled (not $.Values.general.hibernate) }}
      - path: /alfresco
        pathType: Prefix
        backend:
          service:
            name: acs-service
            port:
              number: 30000
      {{- end }}
      {{- if and $.Values.share.enabled $.Values.share.ingress.enabled (not $.Values.general.hibernate) }}
      - path: /share
        pathType: Prefix
        backend:
          service:
            name: share-service
            port:
              number: 30100
      {{- end }}
      {{- if and $.Values.digitalWorkspace.enabled $.Values.digitalWorkspace.ingress.enabled (not $.Values.general.hibernate) }}
      - path: {{ $.Values.digitalWorkspace.basePath }}
        pathType: Prefix
        backend:
          service:
            name: digital-workspace-service
            port:
              number: 30200
      {{- end }}
      {{- if and $.Values.ooi.enabled $.Values.ooi.ingress.enabled (not $.Values.general.hibernate) }}
      - path: /ooi-service
        pathType: Prefix
        backend:
          service:
            name: ooi-service
            port:
              number: 30500
      {{- end }}
      {{- if $.Values.ingress.blockedPaths.enabled }}
      {{- range $.Values.ingress.blockedPaths.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: nginx-default-service
            port:
              number: 30403
      {{- end }}
      {{- end }}
      {{- if and $.Values.ingress.additionalPaths (not $.Values.general.hibernate) }}
      {{ toYaml $.Values.ingress.additionalPaths | nindent 6 }}
      {{- end }}
  {{- end }}
  {{- if and .Values.syncService.enabled (not .Values.general.hibernate) }}
  - host: {{ required "If sync Services are enabled a specific host for sync services must be specified in values.ingress.syncServiceHost" .Values.ingress.syncServiceHost }}
    http:
      paths:
        - path: /alfresco
          pathType: Prefix
          backend:
            service:
              name: sync-service-service
              port:
                number: 30400
  {{- end }}
