# Defines the deployment for the alfresco content repository app
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alfresco-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.ingress.ingressAnnotations}}
    {{ toYaml .Values.ingress.ingressAnnotations | nindent 4 }}
    {{- end }}
spec:
  {{- if eq .Values.ingress.protocol "https" }}
  tls:
    - hosts:
        # Provide the desired host
        - {{ required "A host where your alfresco services can be reached on must be specified in values.ingress.host" .Values.ingress.host }}
        {{- if .Values.syncService.enabled }}
        - {{ required "If sync Services are enabled a specific host for sync services must be specified in values.ingress.syncServiceHost" .Values.ingress.syncServiceHost }}
        {{- end }}
      # Provide a unique secret to store the SSL credentials
      secretName: tls-alfresco-{{ .Release.Name }}-secret
  {{- end }}
  {{- if  .Values.ingress.defaultBackend }}
  defaultBackend:
    service:
      name: {{ .Values.ingress.defaultBackend.service }}
      port:
        number: {{ .Values.ingress.defaultBackend.port }}
  {{- end }}
  rules:
  - host: {{ required "A host where your alfresco services can be reached on must be specified in values.ingress.host" .Values.ingress.host }}
    http:
      paths:
      {{- if .Values.general.hibernate }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-default-service
            port:
              number: 30403
      {{- else if .Values.ingress.defaultPath }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.defaultPath.service }}
            port:
              number: {{ .Values.ingress.defaultPath.port }}
      {{- end }}
      {{- if and .Values.acs.ingress.enabled (not .Values.general.hibernate) }}
      - path: /alfresco
        pathType: Prefix
        backend:
          service:
            name: acs-service
            port:
              number: 30000
      {{- end }}
      {{- if and .Values.share.enabled .Values.share.ingress.enabled (not .Values.general.hibernate) }}
      - path: /share
        pathType: Prefix
        backend:
          service:
            name: share-service
            port:
              number: 30100
      {{- end }}
      {{- if and .Values.digitalWorkspace.enabled .Values.digitalWorkspace.ingress.enabled (not .Values.general.hibernate) }}
      - path: {{ .Values.digitalWorkspace.basePath }}
        pathType: Prefix
        backend:
          service:
            name: digital-workspace-service
            port:
              number: 30200
      {{- end }}
      {{- if and .Values.ooi.enabled .Values.ooi.ingress.enabled (not .Values.general.hibernate) }}
      - path: /ooi-service
        pathType: Prefix
        backend:
          service:
            name: ooi-service
            port:
              number: 30500
      {{- end }}
      {{- if .Values.ingress.blockedPaths.enabled }}
      {{- range .Values.ingress.blockedPaths.paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: nginx-default-service
            port:
              number: 30403
      {{- end }}
      {{- end }}
      {{- if and .Values.ingress.additionalPaths (not .Values.general.hibernate) }}
      {{ toYaml .Values.ingress.additionalPaths | nindent 6 }}
      {{- end }}
  {{- if and .Values.syncService.enabled (not .Values.general.hibernate) }}
  - host: {{ required "If sync Services are enabled a specific host for sync services must be specified in values.ingress.syncServiceHost" .Values.ingress.syncServiceHost }}
    http:
      paths:
        - path: /alfresco
          pathType: Prefix
          backend:
            service:
              name: sync-service-service
              port:
                number: 30400
  {{- end }}
