apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: nginx-default
data:
  nginx.conf: |
    worker_processes  1;
    
    events {
      worker_connections  1024;
    }
    http{
      log_format xenit_json escape=json '{ "time":"$time_iso8601","timestamp":$msec,"responseStatus":$status,"type":"access","requestTime":"$request_time","requestMethod":"$request_method","remoteAddr":"$remote_addr","requestUri":"$request" }';
      access_log /var/log/nginx/access.log xenit_json;
      server {
        listen 80;
        server_name _;
        location /ngnxhealth {
          add_header 'Content-Type' 'application/json';
          access_log off;
          return 200 '{"status":"UP"}';
        }
        {{- if .Values.ingress.blockedPaths.enabled -}}
        {{- range $.Values.ingress.blockedPaths.paths }}
        location {{ . }} {
          return 403 'Forbidden';
        }
        {{- end }}
        {{- end }} 
        location / {
          return 404 'Sorry, this page is not served here.';
        }
      }
    }

