{{- if .Values.ingress.blockAcsSolrApi -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-403-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: nginx-403
data:
  nginx.conf: |
    worker_processes  1;
    
    events {
      worker_connections  1024;
    }
    http{
      server {
        listen 80;
        server_name _;
    
        location / {
          return 403 'Forbidden';
        }
      }
    }
{{- end }}
