apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: nginx-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-default
  template:
    metadata:
      annotations:
      {{- if .Values.general.hibernate }}
        hibernated: 'true'
      {{- end }}
      labels:
        app: nginx-default
    spec:
      {{- if .Values.ingress.nginx.priorityClassName }}
      priorityClassName: {{ .Values.ingress.nginx.priorityClassName }}
      {{- end }}
      containers:
        - name: nginx
          image: {{ .Values.ingress.nginx.image.registry }}/{{ .Values.ingress.nginx.image.repository }}:{{ .Values.ingress.nginx.image.tag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              {{ toYaml .Values.ingress.nginx.resources.requests | nindent 14 }}
            limits:
              memory: 256Mi
      volumes:
        - name: config-volume
          configMap:
            name: nginx-default-configmap