{{- if .Values.ingress.blockAcsSolrApi -}}
apiVersion: v1
kind: Service
metadata:
  name: nginx-403-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if .Values.general.serviceType }}
  type: {{ .Values.general.serviceType }}
  {{- end }}
  selector:
    app: nginx-403
  ports:
    - port: 30403
      targetPort: 80
      protocol: TCP
{{- end }}