apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-default
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: nginx-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-default
  template:
    metadata:
      labels:
        app: nginx-default
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-default-configmap