general:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  db: {}
  cni: cilium
  networkPolicies:
    enabled: false
  secrets:
    acs:
      selfManaged: false
    mq:
      selfManaged: false
    db:
      selfManaged: false
    imageCredentials:
      selfManaged: false

ingress:
  protocol: 'https'
  ingressAnnotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"

acs:
  replicas: 1
  registry: 'xenit'
  repository: 'alfresco-repository-community'
  tag: '7.2.0'
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "2Gi"
      cpu: "2"
  dbUrl: 'jdbc:postgresql://postgresql-service:5432/alfresco'
  dbDriver: 'org.postgresql.Driver'
  sharePort: '443'
  shareProtocol: 'https'
  livenessProbe:
    failureThreshold: 1
    initialDelaySeconds: 130
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 10
  readinessProbe:
    failureThreshold: 6
    initialDelaySeconds: 60
    periodSeconds: 20
    successThreshold: 1
    timeoutSeconds: 10

digitalWorkspace:
  enabled: true
  replicas: 1
  registry: 'quay.io/alfresco'
  repository: 'alfresco-digital-workspace'
  tag: '2.4.2-adw'
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
  basePath: "/workspace"

share:
  enabled: true
  replicas: 1
  registry: 'xenit'
  repository: 'alfresco-share-community'
  tag: '7.0'
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.5"

mq:
  enabled: true
  replicas: 1
  registry: 'alfresco'
  repository: 'alfresco-activemq'
  tag: '5.16.1'
  strategy:
    type: Recreate
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"

postgresql:
  enabled: true
  registry: 'xenit'
  repository: 'postgres'
  tag: 'latest'
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"

solr:
  enabled: true
  replicas: 2
  registry: 'xenit'
  repository: 'alfresco-solr6-xenit'
  tag: '2.0.6'
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"

transformServices:
  enabled: true
  sharedFileStore:
    replicas: 1
    registry: 'alfresco'
    repository: 'alfresco-shared-file-store'
    tag: '0.16.1'
    strategy:
      type: RollingUpdate
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
  transformCoreAio:
    replicas: 1
    registry: 'alfresco'
    repository: 'alfresco-transform-core-aio'
    tag: 'latest'
    strategy:
      type: RollingUpdate
    resources:
      requests:
        memory: "256Mi"
        cpu: "150m"
  transformRouter:
    replicas: 1
    registry: 'quay.io/alfresco'
    repository: 'alfresco-transform-router'
    tag: '1.5.2'
    strategy:
      type: RollingUpdate
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"

syncService:
  enabled: false
  replicas: 1
  registry: 'quay.io/alfresco'
  repository: 'service-sync'
  tag: '3.4.0'
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
      
ooi:
  enabled: false
  replicas: 1
  registry: 'quay.io/alfresco'
  repository: 'alfresco-ooi-service'
  tag: '1.1.2'
  strategy:
    type: RollingUpdate
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
        
persistentStorage:
  alfresco:
    enabled: true
    storageClassName: "" # Standard for local / scw-bssd for scaleway / efs-storage-class for efs
    storage: 3
    efs:
      volumeHandle: ""
  postgres:
    enabled: true
    storageClassName: ""
    storage: 2
    efs:
      volumeHandle: ""
  solr:
    enabled: true
    storageClassName: ""
    storage: 3
    efs:
      volumeHandle: ""
  sharedFileStore:
    enabled: true
    storageClassName: ""
    storage: 2
    efs:
      volumeHandle: ""
  mq:
    enabled: true
    storageClassName: ""
    storage: 1
    efs:
      volumeHandle: ""