{{- if and (.Values.digitalWorkspace.enabled) (.Values.general.enterprise) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-workspace
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: digital-workspace
spec:
  {{- if .Values.general.hibernate }}
  replicas: 0
  {{- else }}
  replicas: {{ .Values.digitalWorkspace.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: digital-workspace
  strategy:
    {{- if eq .Values.digitalWorkspace.strategy.type "Recreate" }}
    type: {{ .Values.digitalWorkspace.strategy.type }}
    {{- else }}
    {{ toYaml .Values.general.strategy | nindent 4 }}
    {{- end }}
  {{- if .Values.digitalWorkspace.serviceAccount }}
  serviceAccountName: {{ .Values.digitalWorkspace.serviceAccount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: digital-workspace
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/digital-workspace/digital-workspace-config.yaml") . | sha256sum }}
        {{- include "globalPodAnnotations" . | indent 8 }}
        {{- if .Values.digitalWorkspace.podAnnotations }}
        {{ toYaml .Values.digitalWorkspace.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: digital-workspace-container
          image: {{ .Values.digitalWorkspace.image.registry }}/{{ .Values.digitalWorkspace.image.repository }}:{{ .Values.digitalWorkspace.image.tag }}
          imagePullPolicy: {{ .Values.digitalWorkspace.imagePullPolicy | default "IfNotPresent" }}
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: {{ .Values.digitalWorkspace.basePath }}
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 4
          readinessProbe:
            failureThreshold: 4
            httpGet:
              path: {{ .Values.digitalWorkspace.basePath }}
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
          envFrom:
            - configMapRef:
                name: digital-workspace-configmap
            {{- if .Values.digitalWorkspace.envFrom }}
            {{ toYaml .Values.digitalWorkspace.envFrom | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8080
              protocol: TCP
          {{- if or (.Values.digitalWorkspace.resources.requests) ((.Values.digitalWorkspace.resources.limits)) }}
          resources:
            {{- if .Values.digitalWorkspace.resources.requests }}
            requests:
            {{ toYaml .Values.digitalWorkspace.resources.requests | nindent 14 }}
            {{- end }}
            {{- if .Values.digitalWorkspace.resources.limits }}
            limits:
            {{ toYaml .Values.digitalWorkspace.resources.limits | nindent 14 }}
            {{- end }}
          {{- end }}
      imagePullSecrets:
        {{- if .Values.general.imagePullSecrets}}
        {{ toYaml .Values.general.imagePullSecrets | nindent 8 }}
        {{- end }}
        {{- if .Values.digitalWorkspace.imagePullSecrets}}
        {{ toYaml .Values.digitalWorkspace.imagePullSecrets | nindent 8 }}
        {{- end }}
{{- end }}