{{- if .Values.digitalWorkspace.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: digital-workspace-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: digital-workspace
  ports:
      - protocol: TCP
        port: 30200
        targetPort: 8080
  {{- if .Values.global.serviceType }}
  type: {{ .Values.global.serviceType }}
  {{- end }}
{{- end }}