{{- if  and (not .Values.general.secrets.mq.selfManaged) (.Values.mq.enabled) (.Values.general.enterprise) }}
{{- $secret_name := "mq-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}

data:
  # try to get the old secret and sync-service-configmap
  # keep in mind, that a dry-run only returns an empty map
  {{- $old_mq_sec := lookup "v1" "Secret" .Release.Namespace $secret_name }}

  # check, if a secret isn't already set and no user is passed
  {{- if and (not $old_mq_sec) (not $old_mq_sec.data) (not .Values.mq.adminLogin) }}
  {{- $generated_mq_user := randAlphaNum 20 | b64enc -}}
  # if not set and not passed, then generate a new user
  ACTIVEMQ_ADMIN_LOGIN: {{ $generated_mq_user }}
  # Setting the data to both be compatible with the Postgres Pods and the ACS Pods
  GLOBAL_messaging.broker.username: {{ $generated_mq_user }}
  # check if the secret exists and no user is passed
  {{- else if and ($old_mq_sec) ($old_mq_sec.data) (not .Values.mq.adminLogin) }}
  # if set and not passed, then use the old value
  ACTIVEMQ_ADMIN_LOGIN: {{ index $old_mq_sec.data "ACTIVEMQ_ADMIN_LOGIN" }}
  GLOBAL_messaging.broker.username: {{ index $old_mq_sec.data "GLOBAL_messaging.broker.username" }}
  {{- else }}
  ACTIVEMQ_ADMIN_LOGIN: {{ .Values.mq.adminLogin | b64enc }}
  GLOBAL_messaging.broker.username: {{ .Values.mq.adminLogin | b64enc }}
  {{- end }}

  # check, if a secret isn't already set and no password is passed
  {{- if and (not $old_mq_sec) (not $old_mq_sec.data) (not .Values.mq.adminPassword) }}
  {{- $generated_mq_password := randAlphaNum 20 | b64enc -}}
  # if not set and not passed, then generate a new password
  ACTIVEMQ_ADMIN_PASSWORD: {{ $generated_mq_password }}
  # Setting the data to both be compatible with the Postgres Pods and the ACS Pods
  GLOBAL_messaging.broker.password: {{ $generated_mq_password }}
  # check if the secret exists and no password is passed
  {{- else if and ($old_mq_sec) ($old_mq_sec.data) (not .Values.mq.adminPassword) }}
  # if set and not passed, then use the old value
  ACTIVEMQ_ADMIN_PASSWORD: {{ index $old_mq_sec.data "ACTIVEMQ_ADMIN_PASSWORD" }}
  GLOBAL_messaging.broker.password: {{ index $old_mq_sec.data "GLOBAL_messaging.broker.password" }}
  {{- else }}
  ACTIVEMQ_ADMIN_PASSWORD: {{ .Values.mq.adminPassword | b64enc }}
  GLOBAL_messaging.broker.password: {{ .Values.mq.adminPassword | b64enc }}
  {{- end }}
{{- end }}