{{- if .Values.mq.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: mq-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.mq.serviceAnnotations }}
    {{ toYaml .Values.mq.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: mq
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
{{- end }}