{{- if .Values.mq.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: mq-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: mq
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
{{- end }}