{{- if .Values.mq.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: mq-secret
  namespace: {{ .Release.Namespace | quote }}
data:
  ACTIVEMQ_ADMIN_LOGIN: {{ required "When the MQ is enabled you need to provide a mq admin username in values.mq.adminLogin" .Values.mq.adminLogin | b64enc }}
  ACTIVEMQ_ADMIN_PASSWORD: {{ required "When the MQ is enabled you need to provide a mq admin password in values.mq.adminPassword" .Values.mq.adminPassword | b64enc }}
{{- end }}