{{- if and (.Values.general.networkPolicies.enabled) (.Values.mq.enabled) (.Values.general.enterprise) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: mq-from-transform-core-aio
spec:
  podSelector:
    matchLabels:
      app: mq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: transform-core-aio
      ports:
        - protocol: TCP
          port: 61616
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: mq-from-transform-router
spec:
  podSelector:
    matchLabels:
      app: mq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: transform-router
      ports:
        - protocol: TCP
          port: 61616
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: mq-from-acs
spec:
  podSelector:
    matchLabels:
      app: mq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 61616
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: mq-from-sync-service
spec:
  podSelector:
    matchLabels:
      app: mq
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: sync-service
      ports:
        - protocol: TCP
          port: 61616
---
{{- end }}