{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.postgresql.serviceAnnotations }}
    {{ toYaml .Values.postgresql.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: postgresql
  ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
{{- end }}