{{- if .Values.syncService.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-service-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sync-service
data:
  JAVA_OPTS: >-
    -Dsql.db.driver={{ .Values.acs.dbDriver }}
    -Dsql.db.url={{ .Values.acs.dbUrl }}
    -Dsql.db.username=$DB_USERNAME
    -Dsql.db.password=$DB_PASSWORD
    -Drepo.hostname=acs-service
    -Drepo.port=30000
    -Dmessaging.broker.host=mq-service
    -Dmessaging.broker.port=61616
    -Dmessaging.broker.protocol=tcp
    -Dmessaging.username=$ACTIVEMQ_ADMIN_LOGIN
    -Dmessaging.password=$ACTIVEMQ_ADMIN_PASSWORD
    -Ddw.server.applicationConnectors[0].type=http
    -Dsync.metrics.reporter.graphite.enabled=false
{{- end }}