{{- if and (.Values.syncService.enabled) (gt .Values.syncService.replicas 1.0) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sync-service-pdb
  namespace: {{ .Release.Namespace | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sync-service
{{- end }}