{{- if .Values.general.networkPolicies.enabled }}
{{- if .Values.transformServices.enabled }}
---
{{- if .Values.mq.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: transform-core-aio-to-mq
spec:
  podSelector:
    matchLabels:
      app: transform-core-aio
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mq
      ports:
        - protocol: TCP
          port: 61616
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: transform-core-aio-to-shared-file-store
spec:
  podSelector:
    matchLabels:
      app: transform-core-aio
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: shared-file-store
      ports:
        - protocol: TCP
          port: 8099
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: transform-core-aio-from-acs
spec:
  podSelector:
    matchLabels:
      app: transform-core-aio
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 8090
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: transform-core-aio-from-transform-router
spec:
  podSelector:
    matchLabels:
      app: transform-core-aio
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: transform-router
      ports:
        - protocol: TCP
          port: 8090
{{- end }}
{{- end }}