{{- if and (.Values.transformServices.enabled) (.Values.transformServices.transformCoreAio.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: transform-core-aio-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.transformServices.transformCoreAio.serviceAnnotations }}
    {{ toYaml .Values.transformServices.transformCoreAio.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: transform-core-aio
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8090
{{- end }}