---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: tranform-router-to-transform-core-aio
spec:
  podSelector:
    matchLabels:
      app: transform-router
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: transform-core-aio
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: tranform-router-to-mq
spec:
  podSelector:
    matchLabels:
      app: transform-router
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mq
---
