{{- if .Values.transformServices.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: transform-router-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.transformServices.transformRouter.serviceAnnotations }}
    {{ toYaml .Values.transformServices.transformRouter.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: transform-router
  ports:
      - protocol: TCP
        port: 30500
        targetPort: 8095
{{- end }}