{{- if and (.Values.transformServices.enabled) (.Values.transformServices.transformRouter.enabled) (.Values.general.enterprise) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: transform-router-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: transform-router
data:
  {{- if .Values.mq.enabled }}
  ACTIVEMQ_URL: 'nio://mq-service:61616'
  {{- end }}
  CORE_AIO_URL: "http://transform-core-aio-service:80"
  FILE_STORE_URL: "http://shared-file-store-service:80/alfresco/api/-default-/private/sfs/versions/1/file"
  {{- if .Values.transformServices.transformRouter.additionalEnvironmentVariables }}
  {{ toYaml .Values.transformServices.transformRouter.additionalEnvironmentVariables | nindent 2 }}
  {{- end }}
{{- end }}