{{- if .Values.general.networkPolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: share-to-acs
spec:
  podSelector:
    matchLabels:
      app: share
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 30000
        - protocol: TCP
          port: 8443
{{- end }}