{{- if .Values.share.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: share
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: share
spec:
  replicas: {{ .Values.share.replicas }}
  selector:
    matchLabels:
      app: share
  strategy:
    {{- if eq .Values.share.strategy.type "Recreate" }}
    type: {{ .Values.share.strategy.type }}
    {{- else }}
    {{ toYaml .Values.general.strategy | nindent 4 }}
    {{- end }}
  {{- if .Values.share.serviceAccount }}
  serviceAccountName: {{ .Values.share.serviceAccount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: share
      annotations:
        checksum/share-config: {{ include (print $.Template.BasePath "/share/share-config.yaml") . | sha256sum }}
        {{- include "globalPodAnnotations" . | indent 8 }}
        {{- if .Values.share.podAnnotations }}
        {{ toYaml .Values.share.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: share-container
        image: {{ .Values.share.image }}
        imagePullPolicy: {{ .Values.share.imagePullPolicy | default "IfNotPresent" }}
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 20
        envFrom:
          - configMapRef:
              name: share-configmap
        ports:
          - containerPort: 8080
            protocol: TCP
        {{- if or (.Values.share.resources.requests) ((.Values.share.resources.limits)) }}
        resources:
          {{- if .Values.share.resources.requests }}
          requests:
          {{ toYaml .Values.share.resources.requests | nindent 12 }}
          {{- end }}
          {{- if .Values.share.resources.limits }}
          limits:
          {{ toYaml .Values.share.resources.limits | nindent 12 }}
          {{- end }}
        {{- end }}
      imagePullSecrets:
        {{- if .Values.general.imagePullSecrets}}
        {{ toYaml .Values.general.imagePullSecrets | nindent 8 }}
        {{- end }}
{{- end }}