{{- if .Values.share.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: share-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.share.serviceAnnotations }}
    {{ toYaml .Values.share.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: share
  ports:
      - protocol: TCP
        port: 30100
        targetPort: 8080
  {{- if .Values.general.serviceType }}
  type: {{ .Values.general.serviceType }}
  {{- end }}
{{- end }}