{{- if and (.Values.transformServices.enabled) (.Values.transformServices.sharedFileStore.enabled) (.Values.general.networkPolicies.enabled)  }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: shared-file-store-from-acs
spec:
  podSelector:
    matchLabels:
      app: shared-file-store
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: acs
      ports:
        - protocol: TCP
          port: 8099
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: shared-file-store-from-aio
spec:
  podSelector:
    matchLabels:
      app: shared-file-store
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: transform-core-aio
      ports:
        - protocol: TCP
          port: 8099
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: shared-file-store-from-transform-router
spec:
  podSelector:
    matchLabels:
      app: shared-file-store
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: transform-router
      ports:
        - protocol: TCP
          port: 8099
---
{{- end }}