{{- if .Values.transformServices.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: shared-file-store-service
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if .Values.transformServices.sharedFileStore.serviceAnnotations }}
    {{ toYaml .Values.transformServices.sharedFileStore.serviceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: shared-file-store
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8099
{{- end }}