{{- if .Values.transformServices.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-file-store-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: shared-file-store
data:
  livenessPercent: "150"
  livenessSavePeriodSeconds: "600"
  {{- if .Values.transformServices.sharedFileStore.additionalEnvironmentVariables }}
  {{ toYaml .Values.transformServices.sharedFileStore.additionalEnvironmentVariables | nindent 2 }}
  {{- end }}
{{- end }}