{{- if .Values.transformServices.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-file-store
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- include "globalAnnotations" . | indent 4 }}
    {{- if .Values.transformServices.sharedFileStore.podAnnotations }}
    {{ toYaml .Values.transformServices.sharedFileStore.podAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: shared-file-store
spec:
  replicas: {{ .Values.transformServices.sharedFileStore.replicaCount }}
  selector:
    matchLabels:
      app: shared-file-store
  strategy:
    {{- if eq .Values.transformServices.sharedFileStore.strategy.type "Recreate" }}
    type: {{ .Values.transformServices.sharedFileStore.strategy.type }}
    {{- else }}
    {{ toYaml .Values.global.strategy | nindent 4 }}
    {{- end }}
  {{- if .Values.transformServices.sharedFileStore.serviceAccount }}
  serviceAccountName: {{ .Values.transformServices.sharedFileStore.serviceAccount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: shared-file-store
    spec:
      containers:
        - name: shared-file-store-container
          image: {{ .Values.transformServices.sharedFileStore.image.repository }}{{ if .Values.transformServices.sharedFileStore.image.tag }}:{{ .Values.transformServices.sharedFileStore.image.tag }}{{ end }}
          imagePullPolicy: {{ .Values.transformServices.sharedFileStore.image.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: shared-file-store-configmap
          ports:
            - containerPort: 8099
              protocol: TCP
          resources:
            requests:
              memory: "1000Mi"
          volumeMounts:
            - name: data
              mountPath: /tmp/Alfresco
      imagePullSecrets:
        - name: alfrescocred
        {{- if .Values.global.imagePullSecrets}}
        {{ toYaml .Values.global.imagePullSecrets | nindent 8 }}
        {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shared-file-store-pvc
{{- end }}