name: 'Continuous Integration'
on:
  push:
    paths:
      - 'xenit-alfresco/**'
    tags:
      - v*
jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3
      - name: Package Helm Chart
        run: |
          helm package xenit-alfresco --version `echo ${GITHUB_REF#refs/tags/} | cut -c 2-`
          ls| grep -e '^alfresco.*\.tgz' |  xargs -I '{}' mv {} ./alfresco.tgz
          ls
      - name: publish to cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'helm'
          owner: 'xenit'
          repo: 'open-source'
          file: 'alfresco.tgz'