name: 'Continuous Integration'
on:
  push:
  pull_request:
    paths:
      - 'xenit-alfresco/**'
    branches:
      - main
jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v1
      - name: Package Helm Chart
        run: |
          helm package xenit-alfresco
      - name: publish to cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'helm'
          owner: 'xenit-TRG'
          repo: 'alfresco'
          republish: 'true'
          file: 'alfresco.tar.gz'