name: 'Continuous Integration'
on:
  push:
    paths:
      - 'xenit-alfresco/**'
    tags:
      - v*
jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Install Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1
      - name: Package Helm Chart
        run: |
          helm package xenit-alfresco --version `echo ${GITHUB_REF#refs/tags/} | cut -c 2-`
          ls| grep -e '^alfresco.*\.tgz' |  xargs -I '{}' mv {} ./alfresco.tgz
          ls
      - name: publish to cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: 'push'
          format: 'helm'
          owner: 'xenit'
          repo: 'open-source'
          file: 'alfresco.tgz'