{{- if and (.Values.general.networkPolicies.enabled) (.Values.solr.enabled) (.Values.solr.autoBackup.enabled) -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: solr-backup-cron-job-to-solr
spec:
  podSelector:
    matchLabels:
      app: solr-backup-cron-job
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: solr
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: solr-from-solr-backup-cron-job
spec:
  podSelector:
    matchLabels:
      app: solr
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: solr-backup-cron-job
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
{{- end }}