{{- if and (.Values.solr.enabled) (.Values.solr.autoBackup.enabled) (not .Values.general.hibernate) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace }}
  name: solr-backup-cron
spec:
  successfulJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: {{ .Values.solr.autoBackup.cron }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: solr-backup-cron-job
          namespace: {{ .Release.Namespace }}
          labels:
            app: solr-backup-cron-job
        spec:
          {{- if .Values.solr.autoBackup.priorityClassName }}
          priorityClassName: {{ .Values.solr.autoBackup.priorityClassName }}
          {{- end }}
          containers:
            - name: curlimage
              image: {{ .Values.solr.autoBackup.image.registry }}/{{ .Values.solr.autoBackup.image.repository }}@{{ .Values.solr.autoBackup.image.digest }}
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  response=$(curl -s $BACKUP_URL)
                  if echo "$response" | grep -q "\"exception\""; then
                    echo "Failure detected: Exception found in response."
                    echo "$response"
                    exit 22
                  else
                    echo "Success: No exception found.\n $response"
                    exit 0
                  fi
              args:
                - curl $BACKUP_URL
              env:
                - name: BACKUP_URL
                  value: {{ .Values.solr.autoBackup.backupUrl }}
          restartPolicy: OnFailure
{{- end }}